### ISSUE TITLE
OptiFine does not download anymore since website update

### ISSUE THREAD

**Issue by JohnnyDabb2** [Janrupf/mod-director#12]
I have been using this mod to get Optifine since the early days of my pack.  It just started crashing recently and I don't know why.

[latest.log](https://github.com/Janrupf/mod-director/files/5357746/latest.log)

**Comment by Janrupf** [comment]
Looks like the OptiFine dev changed their website. The new version should be ``"follows": ["OptiFine 1.12.2 HD U F5"]``

**Comment by ACGaming** [comment]
Indeed, the website has changed after years. This is my current working config for the latest 1.12.2 OptiFine:

`{
    "url": "https://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_F6_pre1.jar",
    "follows": ["preview OptiFine 1.12.2 HD U F6 pre1"],
    "fileName": "OptiFine_1.12.2_HD_U_F6_pre1_MOD.jar",
    "options": {
        "launchwrapperTweakerForceNext": true
    }
}`

**Comment by JohnnyDabb2** [comment]
thanks.
