### ISSUE TITLE
support other files than mods

### ISSUE THREAD

**Issue by HansWasser** [Janrupf/mod-director#6]
It would be nice to be able to download any file that might be necessary and have it saved wherever in the minecraft installation it's needed. It would also be grade if files could be marked as optional and the user get's asked about them before download. That would allow optional mods in modpacks and preconfigured game options with profiles.

**Comment by theshadowake** [comment]
I'd love to be able to have minetweaker scripts download to the /scripts folder, or config files to go to /configs. As a modpack dev that would save me time deploying fixes quickly without needing to upload the whole pack to curse and wait for approval. Would be a godsend.

**Comment by Janrupf** [comment]
> As a modpack dev that would save me time deploying fixes quickly without needing to upload the whole pack to curse and wait for approval. Would be a godsend.
Quick fixing things is actually something I have not thought about yet. This requires a new system, since currently files are only updated when they are missing or don't match the checksum. I will probably add an option for `downloadAlways`, just be careful with it.

**Comment by CrankySupertoon** [comment]
I don't think this is smart. Okay, ModDirectory let's download VIRUS.exe on the computer now.

**Comment by theshadowake** [comment]
> 
> 
> I don't think this is smart. Okay, ModDirectory let's download VIRUS.exe on the computer now.

And what would then run virus.exe, a virus needs a way to actually run... it's no different to doewnloading any minecraft mod.
