### ISSUE TITLE
server crashes when running the mod

### ISSUE THREAD

**Issue by HansWasser** [Janrupf/mod-director#9]
I just tried out if the mod would also work on a server, as with the upcomming feature of live modpack updating it'd be a pain for any server admin if the clients update themselves without the server doing so too. Turns out it doesn't work...
Here's the log file
[latest.log](https://github.com/Janrupf/mod-director/files/4730235/latest.log)

**Comment by TigerWalts** [comment]
I don't know which mod the **tkkl.url.json** is supposed to be downloading but it may not be server compatible and this causing the crash when ModDirector tries to load it.

Had the same problem with the Awakening - Sky of Diamonds pack as it tries to load Optifine.

It would be beneficial for ModDirector to support a **side** option, with values `BOTH`, `CLIENT`, `SERVER`. e.g.

```json
{
    "url": "http://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_F5.jar",
    "follows": ["Download OptiFine_1.12.2_HD_U_F5.jar"],
    "fileName": "Optifine_1.12.2_HD_U_F5.jar",
    "options": {
        "launchwrapperTweakerForceNext": true
        "side": "CLIENT"
    }
}
```

This way the same configs can be placed on server and client.

**Comment by HansWasser** [comment]
The mod that's supposed to be downloaded is server compatible. To be fair it is not compatible with the minecraft version the server is running but the server crashes before anything is downloaded. If the server crashed due to an incompatibility with the mod it would have to be downloaded in the first place.

**Comment by Janrupf** [comment]
> I don't know which mod the **tkkl.url.json** is supposed to be downloading but it may not be server compatible and this is causing the crash when ModDirector tries to load it.
> 
> Had the same problem with the Awakening - Sky of Diamonds pack as it tries to load Optifine.
> 
> It would be beneficial for ModDirector to support a **side** option, with values `BOTH`, `CLIENT`, `SERVER`. e.g.
> 
> ```json
> {
>     "url": "http://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_F5.jar",
>     "follows": ["Download OptiFine_1.12.2_HD_U_F5.jar"],
>     "fileName": "Optifine_1.12.2_HD_U_F5.jar",
>     "options": {
>         "launchwrapperTweakerForceNext": true,
>         "side": "CLIENT"
>     }
> }
> ```
> 
> This way the same configs can be placed on server and client.

I like the idea with the `"side"` config

**Comment by Janrupf** [comment]
https://github.com/Janrupf/mod-director/wiki/Metadata#side-config
